apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ./../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: book-service
  name: book-service
spec:
  ports:
    - name: "5006"
      port: 5006
      targetPort: 5006
  selector:
    io.kompose.service: book-service
