apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ./../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: borrow-service
  name: borrow-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: borrow-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ./../compose.yaml
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: borrow-service
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: env
          image: aadhithya123/borrow-service
          imagePullPolicy: Always
          name: borrowservice
          ports:
            - containerPort: 5003
              protocol: TCP
      restartPolicy: Always
