apiVersion: v1
data:
  POSTGRES_DB: library
  POSTGRES_HOST: database
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: postgres
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_DEFAULT_USER: guest
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: book-service-env
  name: env
