apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f ./../compose.yaml
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: user-service
  name: user-service
spec:
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: user-service
